apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- namespace.yaml
namespace: nodejs
images:
- name: aks-nodejs-argocd
  newName: ugoben/aks-nodejs-argocd
  newTag: 74566002def188a8b812d100980ba6e54a9b56c9
